apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-master-local-path-provisioner
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - name: local-path-provisioner.service
          enabled: true
          contents: |
            [Unit]
            Description=Create and set SELinux contenxt on local-path-provisioner directory
            Before=kubelet.service

            [Service]
            ExecStart=/bin/mkdir -p /opt/local-path-provisioner && \
                      /usr/bin/chcon -Rt container_file_t /opt/local-path-provisioner

            [Install]
            WantedBy=multi-user.target
